# Generated by Django 2.0.6 on 2018-06-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnent',
            new_name='Comment',
        ),
    ]
