# Generated by Django 2.0.6 on 2018-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_auto_20180613_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='blog_post.Tag'),
        ),
    ]
